// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<AudioOutputDeviceInfo>? listRenderAudioDevices() =>
    RustLib.instance.api.crateApiAudioOutputDeviceListRenderAudioDevices();

class AudioOutputDeviceInfo {
  final String endpointId;
  final String name;
  final bool isDefault;

  const AudioOutputDeviceInfo({
    required this.endpointId,
    required this.name,
    required this.isDefault,
  });

  @override
  int get hashCode => endpointId.hashCode ^ name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioOutputDeviceInfo &&
          runtimeType == other.runtimeType &&
          endpointId == other.endpointId &&
          name == other.name &&
          isDefault == other.isDefault;
}
